- name: Install virtualenv packages
  apt:
    name: [ python3-virtualenv ]
    state: latest

- name: Creates directory
  file:
    path: "{{ autoscaling_home }}"
    state: directory
  become_user: "{{ autoscaling_user }}"

- name: Check if {{ autoscaling_env }}  already installed
  stat:
    path: "{{ autoscaling_home }}/{{ autoscaling_env }}"
  register: virtualenv_installed

- name: Create the initial virtualenv
  command:
    cmd: /usr/bin/virtualenv "{{ autoscaling_home }}/{{ autoscaling_env }}" -p python3.8
    creates: "{{ autoscaling_home }}/{{ autoscaling_env }}"
  become_user: "{{ autoscaling_user }}"
  when: virtualenv_installed.stat.exists == False

- name: Install pip packages
  pip:
    name: [ cython==0.29.32,requests==2.28.1,pyyaml==6.0,pandas==1.5.2,numpy==1.23.5,matplotlib==3.6.2 ]
    virtualenv: "{{ autoscaling_home }}/{{ autoscaling_env }}"
  become_user: "{{ autoscaling_user }}"

- name: Check if {{ autoscaling_env }} installed
  stat:
    path: "{{ autoscaling_home }}/{{ autoscaling_env }}"
  register: virtualenv_installed
  
